# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
    - id: 31
      rpc_config:
          url: https://rootstock-testnet.g.alchemy.com/v2/2_F7dgp4mWUW4d089X4Ttyi0JUAESl_
      start_block: 0 # 6600000
      contracts:
          - name: RecurringPaymentFactory
            address:
                - 0x0C8Fdf41AcF8D4027A537bECE5BCAa3434D92000
            handler: src/EventHandlers.ts
            events:
                - event: PlanCreated(address indexed plan, address indexed payer, address indexed recipient, uint256 amount, uint256 interval, uint256 startTime, string title)
          - name: RecurringPayment
            # No address field - we'll discover these addresses from events
            # address: 0x64748677Bde4c2eEd203Be4E2432De8CB9019593
            handler: src/EventHandlers.ts
            events:
                - event: AmountUpdated(address indexed plan, uint256 oldAmount, uint256 newAmount)
                - event: FundsAdded(address indexed plan, address indexed planOwner, address indexed payer, uint256 amount, uint256 timestamp, string title)
                - event: FundsReceived(address indexed plan, address indexed planOwner, address indexed payer, uint256 amount, uint256 timestamp, string title)
                - event: IntervalUpdated(address indexed plan, uint256 oldInterval, uint256 newInterval)
                - event: PaymentExecuted(address indexed plan, address indexed payer, address indexed recipient, uint256 amount, uint256 timestamp, string title)
                - event: PaymentTaskCreated(address indexed payer, bytes32 taskId, address plan)
                - event: PlanCancelled(address indexed plan, address indexed payer, uint256 refundedAmount, uint256 timestamp)
                - event: PlanPaused(address indexed plan, address indexed payer, uint256 timestamp)
                - event: PlanUnpaused(address indexed plan, address indexed payer, uint256 timestamp)
unordered_multichain_mode: true
